### ISSUE TITLE
Getting codepage error

### ISSUE THREAD

**Issue by isarantis** [mafintosh/srt-to-vtt#2]
Edit: Repo confusion.

**Comment by mafintosh** [comment]
I think you meant to open this issue on a different repo? My module is called srt-to-vtt, not srt2vtt

**Comment by isarantis** [comment]
Oh, yes sorry about that the problem i was having with yours was with the encoding eventualy after passing the files throu the converter i couldn't get ex: greek characters..

Sorry about that my mistake i edited the post.

**Comment by mafintosh** [comment]
Hmm I'm a bit more confused now? Are you it didnt work with my module? Otherwise could you close this?

**Comment by isarantis** [comment]
I tryied working with your module but the problem i was getting was with utf8 encoded files. The encoding broke no matter using encoding options on readfile and write.

Thanks in advance, sorry for the confusion about the first post.

**Comment by mafintosh** [comment]
Could you share a full example of what isn't working?

**Comment by isarantis** [comment]
Using your example:
var srt2vtt = require('srt-to-vtt')
var fs = require('fs')

fs.createReadStream('subs.srt', {encoding: 'utf-8'})
  .pipe(srt2vtt())
  .pipe(fs.createWriteStream('subs.vtt'), {encoding: 'utf-8'})

From: subs.srt:
2
00:00:17,531 --> 00:00:20,697
στη μεγαλύτερη ιστοσελίδα
διαμοιρασμού αρχείων στον κόσμο.

To subs.vtt:
00:00:17.531 --> 00:00:20.697
��� ���������� ����������
������������ ������� ���� �����.

**Comment by mafintosh** [comment]
try removing the encoding option

**Comment by isarantis** [comment]
Tryed both removing encoding option from read and write, but also on  both but the result was the same. 
ps: the srt is utf8

**Comment by isarantis** [comment]
I fixed the error, i was beeing dumb once again and adding wrong encoding to the initial file.

Thanks again

**Comment by mafintosh** [comment]
No worries. Glad you figured it out!
