### ISSUE TITLE
Detect input (.srt) file encoding

### ISSUE THREAD

**Issue by grunjol** [mafintosh/srt-to-vtt#3]
.srt files come from different sources, and there is no rule (or declaration) on character encoding, so its very common to find latin1(iso-8859-1 / cp1252) encoded files.

But vtt [MUST BE UTF-8](https://w3c.github.io/webvtt/#file-structure) encoded.

When input file (using CLI) is a latin1 the output file is not correctly encoded

[tests.zip](https://github.com/mafintosh/srt-to-vtt/files/217787/tests.zip)

**Comment by mafintosh** [comment]
What if put https://github.com/finnp/to-utf-8 inbetween the input the srt-to-vtt?

```
var utf8 = require('to-utf-8')
...

source.pipe(utf8).pipe(srtToVtt)
```

**Comment by grunjol** [comment]
sure, i can do that in my code, but if you want to use srt-to-vtt from CLI this should be done in srt-to-vtt. 

But if the module do srt to vtt and srt COULD BE in non-UTF8 and VTT MUST BE in UTF8, IMHO this should be handled by srt-to-vtt.

I can always send PR and get accepted

**Comment by grunjol** [comment]
after some testing i found `to-utf-8` doesn't recognize correct encoding because it uses `peek-stream` to get the sample to do the detection. because the input is an srt, the first line its always `1` because is the caption number. So, i need to detect first the language, then pass it to utf8(encoding) to do the conversion

**Comment by grunjol** [comment]
Sent PR https://github.com/finnp/to-utf-8/pull/2 to better encoding detection

**Comment by mafintosh** [comment]
send a pr for that change once your pr lands in to-utf-8 :)
