### ISSUE TITLE
Missing ending line

### ISSUE THREAD

**Issue by grunjol** [mafintosh/srt-to-vtt#4]
When the last caption line does not have an empty line the entire caption is missing.

Check test file in #3 

if the last lines ends in single `0A` the entire line is skipped, but if its `0A 0A` its converted

**Comment by grunjol** [comment]
Verified: https://w3c.github.io/webvtt/#file-structure file ending line terminator is optional

**Comment by mafintosh** [comment]
What should the file end with? If you PR a couple of test cases I'll fix it :)

**Comment by grunjol** [comment]
sent PR #5

**Comment by grunjol** [comment]
srt and vtt can end with `\r\n` (last text line terminator) or with '\r\n\r\n' (last text line terminator and file line terminator )
